export const portugueseToEnglish = {
    "inseto": "bug",
    "sombrio": "dark",
    "dragao": "dragon",
    "eletrico": "electric",
    "fada": "fairy",
    "lutador": "fighting",
    "fogo": "fire",
    "voador": "flying",
    "fantasma": "ghost",
    "planta": "grass",
    "terrestre": "ground",
    "gelo": "ice",
    "normal": "normal",
    "venenoso": "poison",
    "psiquico": "psychic",
    "pedra": "rock",
    "aco": "steel",
    "agua": "water",
  };